name: titanic_dependencies
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.8
  - pip>=19.1.1
  - numpy>=1.13.3
  - pandas==0.25.1
  - pip:
      - jsonlines>=1.2.0
      - azureml-sdk==1.17.0
      - azureml-defaults>=1.0.45
      - azureml-monitoring
      - cached-property==1.5.1
      - scikit-learn==0.22.1
      - nteract-scrapbook>=0.2.1
      - pydocumentdb>=2.3.3
      - tqdm==4.32.2
      - pyemd==0.5.1
      - ipywebrtc==0.4.3
      - pre-commit>=1.14.4
      - requests==2.22.0
      - requests-oauthlib==1.2.0
      - joblib
